### ISSUE TITLE
Fresh install of plugin causes error on project config rebuild

### ISSUE THREAD

**Issue by noahjahn** [solspace/craft3-calendar#100]
**Describe the bug or issue you're experiencing**

After fresh installing the calendar plugin, we are no longer able to execute the Craft project config rebuild command due to what appears to be a missing table. I have tested this with a fresh install of the latest version of Craft with Craft Nitro.

**Steps to reproduce**

1. Install Craft Nitro: https://craftcms.com/docs/nitro/2.x/installation.html
2. Setup a project with Craft Nitro: https://craftcms.com/docs/nitro/2.x/usage.html#setting-up-sites
3. Setup your new Craft install
4. Login to the Craft admin
5. Visit the Plugin Store in the Craft Admin
6. Search for the Calendar plugin, and click on the "Try" button in the "Pro" version of the plugin
7. Wait for the plugin to download and install
8. Go to Utilities > Project Config > click the **Rebuild** button
9. See the error!

**Expected behavior**

The project config rebuild should still be able to build project config files from data in the database even after installing the Calendar plugin.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Solo 3.7.32 (This also happens on Pro)
- Calendar Version: 3.3.8
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh install

**Additional context**

See the following stack trace:

```
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "calendarsites"
LINE 1: SELECT calendarSites."id", calendarSites."uid", calendarSite...
               ^ in /app/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT calendar...')
#2 /app/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /app/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#5 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(121): craft\db\Query->all()
#6 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(79): Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->buildCalendarSitesConfig(1)
#7 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(32): Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->buildCalendarConfig()
#8 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(26): Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->buildProjectConfig()
#9 [internal function]: Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->rebuildConfig(Object(craft\events\RebuildConfigEvent))
#10 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\RebuildConfigEvent))
#11 /app/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'rebuild', Object(craft\events\RebuildConfigEvent))
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1251): yii\base\Component->trigger('rebuild', Object(craft\events\RebuildConfigEvent))
#13 /app/vendor/craftcms/cms/src/controllers/ProjectConfigController.php(90): craft\services\ProjectConfig->rebuild()
#14 [internal function]: craft\controllers\ProjectConfigController->actionRebuild()
#15 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('rebuild', Array)
#18 /app/vendor/craftcms/cms/src/web/Application.php(292): yii\base\Module->runAction('project-config/...', Array)
#19 /app/vendor/craftcms/cms/src/web/Application.php(601): craft\web\Application->runAction('project-config/...', Array)
#20 /app/vendor/craftcms/cms/src/web/Application.php(271): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /app/web/index.php(12): yii\base\Application->run()
#23 {main}

Next yii\db\Exception: SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "calendarsites"
LINE 1: SELECT calendarSites."id", calendarSites."uid", calendarSite...
               ^
The SQL being executed was: SELECT calendarSites."id", calendarSites."uid", calendarSites."calendarId", calendarSites."siteId", calendarSites."enabledByDefault", calendarSites."hasUrls", calendarSites."uriFormat", calendarSites."template"
FROM "calendar_calendar_sites" "calendarSites"
WHERE "calendarId"=1
ORDER BY "id" in /app/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT calendar...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT calendar...')
#2 /app/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /app/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#5 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(121): craft\db\Query->all()
#6 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(79): Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->buildCalendarSitesConfig(1)
#7 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(32): Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->buildCalendarConfig()
#8 /app/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/ProjectConfigBundle.php(26): Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->buildProjectConfig()
#9 [internal function]: Solspace\Calendar\Bundles\ProjectConfig\ProjectConfigBundle->rebuildConfig(Object(craft\events\RebuildConfigEvent))
#10 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\RebuildConfigEvent))
#11 /app/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'rebuild', Object(craft\events\RebuildConfigEvent))
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1251): yii\base\Component->trigger('rebuild', Object(craft\events\RebuildConfigEvent))
#13 /app/vendor/craftcms/cms/src/controllers/ProjectConfigController.php(90): craft\services\ProjectConfig->rebuild()
#14 [internal function]: craft\controllers\ProjectConfigController->actionRebuild()
#15 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('rebuild', Array)
#18 /app/vendor/craftcms/cms/src/web/Application.php(292): yii\base\Module->runAction('project-config/...', Array)
#19 /app/vendor/craftcms/cms/src/web/Application.php(601): craft\web\Application->runAction('project-config/...', Array)
#20 /app/vendor/craftcms/cms/src/web/Application.php(271): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /app/web/index.php(12): yii\base\Application->run()
#23 {main}
Additional Information:
Array
(
    [0] => 42P01
    [1] => 7
    [2] => ERROR:  missing FROM-clause entry for table "calendarsites"
LINE 1: SELECT calendarSites."id", calendarSites."uid", calendarSite...
               ^
)
```

**Comment by kjmartens** [comment]
Sorry for the trouble and the delay, @noahjahn. Would you be able to try updating to the latest in the `dev-master` branch? We just committed 2 fixes that should resolve this issue and the other issue you mentioned via private support ticket.

You can do `dev-master as 3.3.8.1`... let me know if it resolves your two issues. 🙂

**Comment by noahjahn** [comment]
@kjmartens Thank you for the reply and quick fix! It appears both issues are resolved in `dev-master`, I'll respond to the private support ticket as well.
