### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by davist11** [solspace/craft3-calendar#12]
I'm in the process of updating a Craft 2 site to Craft 3, and the Calendar migration appeared to go ok. But, when I click into the default calendar (`admin/calendar/calendars/default`), I get the following error:

```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hamilton.craft_calendar_calendar_sites' doesn't exist in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `calenda...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(136): yii\db\Query->all(NULL)
#5 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Services/CalendarsService.php(492): craft\db\Query->all()
#6 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Models/CalendarModel.php(206): Solspace\Calendar\Services\CalendarsService->getCalendarSiteSettings(1)
#7 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php(139): Solspace\Calendar\Models\CalendarModel->getSiteSettings()
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/helpers/Template.php(57): yii\base\Component->__get('siteSettings')
#9 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/d9/d9dda4c74551f8dcbf0fac29a94f3eb4c3a18581df2dca4f04ea3fa61cb913db.php(237): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(Solspace\Calendar\Models\CalendarModel), 'siteSettings', Array, 'any', false, true)
#10 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(193): __TwigTemplate_1e2774c89afa85b68e5966c7dc56d19dc62868f3f49d9fe7a13210d3f22e798a->block_content(Array, Array)
#11 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/ac/acaf91c01bbdd47d489bf203f2d2aa5aef9f5236a8c08bb01fa8cdf3e3f7950c.php(640): Twig_Template->displayBlock('content', Array, Array)
#12 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(193): __TwigTemplate_4f505b1097cc18aa79166d11f2159214fa02d3fa387b119e9ccb9b98aec847c8->block_main(Array, Array)
#13 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/ac/acaf91c01bbdd47d489bf203f2d2aa5aef9f5236a8c08bb01fa8cdf3e3f7950c.php(537): Twig_Template->displayBlock('main', Array, Array)
#14 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(193): __TwigTemplate_4f505b1097cc18aa79166d11f2159214fa02d3fa387b119e9ccb9b98aec847c8->block_body(Array, Array)
#15 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/1a/1aaed9238a2def70862e1e040bdacc7634d7c6f059d8144e79ec3b10199e04d1.php(57): Twig_Template->displayBlock('body', Array, Array)
#16 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_d8142c816efa9a18ab6c3833b6c6be3042aaae6ee9769a6114f47b1f272844fb->doDisplay(Array, Array)
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/8a/8aee160cea6c4f13916e091e6cef57dcf11f6b7fcbc031768341a0f612d1787d.php(40): craft\web\twig\Template->display(Array, Array)
#21 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_88bd80751573a94483f64fc2dcc00d29da8ffa5aab16102d83e739a2e477b888->doDisplay(Array, Array)
#22 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#23 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#25 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/ac/acaf91c01bbdd47d489bf203f2d2aa5aef9f5236a8c08bb01fa8cdf3e3f7950c.php(94): craft\web\twig\Template->display(Array, Array)
#26 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_4f505b1097cc18aa79166d11f2159214fa02d3fa387b119e9ccb9b98aec847c8->doDisplay(Array, Array)
#27 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#28 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#30 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/a7/a708d374947e9a2cb9ed3f728b0b44e69ee3d26a82890e402a05abca6a89e439.php(31): craft\web\twig\Template->display(Array, Array)
#31 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_48d73abfa21a635f3611ed7ddcf0d384f6dc5dc9a3d4e2c9a74dbe3472830f88->doDisplay(Array, Array)
#32 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#33 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#35 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/d9/d9dda4c74551f8dcbf0fac29a94f3eb4c3a18581df2dca4f04ea3fa61cb913db.php(104): craft\web\twig\Template->display(Array, Array)
#36 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_1e2774c89afa85b68e5966c7dc56d19dc62868f3f49d9fe7a13210d3f22e798a->doDisplay(Array, Array)
#37 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#38 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#39 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#40 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(379): craft\web\twig\Template->display(Array)
#41 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#42 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('calendar/calend...', Array)
#43 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('calendar/calend...', Array)
#44 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(113): craft\web\View->renderPageTemplate('calendar/calend...', Array)
#45 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Controllers/CalendarsController.php(287): craft\web\Controller->renderTemplate('calendar/calend...', Array)
#46 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Controllers/CalendarsController.php(74): Solspace\Calendar\Controllers\CalendarsController->renderEditTemplate(Object(Solspace\Calendar\Models\CalendarModel), 'Default')
#47 [internal function]: Solspace\Calendar\Controllers\CalendarsController->actionEditCalendar('default')
#48 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#49 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#50 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('edit-calendar', Array)
#51 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-calendar', Array)
#52 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('calendar/calend...', Array)
#53 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('calendar/calend...', Array)
#54 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(226): yii\web\Application->handleRequest(Object(craft\web\Request))
#55 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#56 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#57 {main}

Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hamilton.craft_calendar_calendar_sites' doesn't exist
The SQL being executed was: SELECT `calendar_calendar_sites`.`id`, `calendar_calendar_sites`.`calendarId`, `calendar_calendar_sites`.`siteId`, `calendar_calendar_sites`.`enabledByDefault`, `calendar_calendar_sites`.`hasUrls`, `calendar_calendar_sites`.`uriFormat`, `calendar_calendar_sites`.`template`
FROM `craft_calendar_calendar_sites` `calendar_calendar_sites`
INNER JOIN `craft_sites` `sites` ON `sites`.`id` = `calendar_calendar_sites`.`siteId`
WHERE `calendar_calendar_sites`.`calendarId`=1
ORDER BY `sites`.`sortOrder` in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `calenda...')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `calenda...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(136): yii\db\Query->all(NULL)
#5 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Services/CalendarsService.php(492): craft\db\Query->all()
#6 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Models/CalendarModel.php(206): Solspace\Calendar\Services\CalendarsService->getCalendarSiteSettings(1)
#7 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php(139): Solspace\Calendar\Models\CalendarModel->getSiteSettings()
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/helpers/Template.php(57): yii\base\Component->__get('siteSettings')
#9 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/d9/d9dda4c74551f8dcbf0fac29a94f3eb4c3a18581df2dca4f04ea3fa61cb913db.php(237): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(Solspace\Calendar\Models\CalendarModel), 'siteSettings', Array, 'any', false, true)
#10 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(193): __TwigTemplate_1e2774c89afa85b68e5966c7dc56d19dc62868f3f49d9fe7a13210d3f22e798a->block_content(Array, Array)
#11 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/ac/acaf91c01bbdd47d489bf203f2d2aa5aef9f5236a8c08bb01fa8cdf3e3f7950c.php(640): Twig_Template->displayBlock('content', Array, Array)
#12 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(193): __TwigTemplate_4f505b1097cc18aa79166d11f2159214fa02d3fa387b119e9ccb9b98aec847c8->block_main(Array, Array)
#13 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/ac/acaf91c01bbdd47d489bf203f2d2aa5aef9f5236a8c08bb01fa8cdf3e3f7950c.php(537): Twig_Template->displayBlock('main', Array, Array)
#14 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(193): __TwigTemplate_4f505b1097cc18aa79166d11f2159214fa02d3fa387b119e9ccb9b98aec847c8->block_body(Array, Array)
#15 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/1a/1aaed9238a2def70862e1e040bdacc7634d7c6f059d8144e79ec3b10199e04d1.php(57): Twig_Template->displayBlock('body', Array, Array)
#16 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_d8142c816efa9a18ab6c3833b6c6be3042aaae6ee9769a6114f47b1f272844fb->doDisplay(Array, Array)
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/8a/8aee160cea6c4f13916e091e6cef57dcf11f6b7fcbc031768341a0f612d1787d.php(40): craft\web\twig\Template->display(Array, Array)
#21 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_88bd80751573a94483f64fc2dcc00d29da8ffa5aab16102d83e739a2e477b888->doDisplay(Array, Array)
#22 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#23 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#25 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/ac/acaf91c01bbdd47d489bf203f2d2aa5aef9f5236a8c08bb01fa8cdf3e3f7950c.php(94): craft\web\twig\Template->display(Array, Array)
#26 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_4f505b1097cc18aa79166d11f2159214fa02d3fa387b119e9ccb9b98aec847c8->doDisplay(Array, Array)
#27 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#28 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#30 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/a7/a708d374947e9a2cb9ed3f728b0b44e69ee3d26a82890e402a05abca6a89e439.php(31): craft\web\twig\Template->display(Array, Array)
#31 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_48d73abfa21a635f3611ed7ddcf0d384f6dc5dc9a3d4e2c9a74dbe3472830f88->doDisplay(Array, Array)
#32 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#33 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#35 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/d9/d9dda4c74551f8dcbf0fac29a94f3eb4c3a18581df2dca4f04ea3fa61cb913db.php(104): craft\web\twig\Template->display(Array, Array)
#36 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(394): __TwigTemplate_1e2774c89afa85b68e5966c7dc56d19dc62868f3f49d9fe7a13210d3f22e798a->doDisplay(Array, Array)
#37 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#38 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#39 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#40 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(379): craft\web\twig\Template->display(Array)
#41 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#42 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('calendar/calend...', Array)
#43 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('calendar/calend...', Array)
#44 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(113): craft\web\View->renderPageTemplate('calendar/calend...', Array)
#45 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Controllers/CalendarsController.php(287): craft\web\Controller->renderTemplate('calendar/calend...', Array)
#46 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Controllers/CalendarsController.php(74): Solspace\Calendar\Controllers\CalendarsController->renderEditTemplate(Object(Solspace\Calendar\Models\CalendarModel), 'Default')
#47 [internal function]: Solspace\Calendar\Controllers\CalendarsController->actionEditCalendar('default')
#48 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#49 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#50 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('edit-calendar', Array)
#51 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-calendar', Array)
#52 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('calendar/calend...', Array)
#53 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('calendar/calend...', Array)
#54 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(226): yii\web\Application->handleRequest(Object(craft\web\Request))
#55 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#56 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#57 {main}
Additional Information:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'hamilton.craft_calendar_calendar_sites' doesn't exist
)
```

**Comment by kjmartens** [comment]
Sorry for the trouble... Calendar 2 Beta 1-4 had no migration path until beta 5. You can try upgrading your whole install again with Beta 5 that is now available (though it seems like you encountered an issue with Freeform that we'll need to investigate, so perhaps you may have to wait on that part as well).

**Comment by davist11** [comment]
I updated to Calendar Beta 5, and I'm still getting the same error as above.

**Comment by kjmartens** [comment]
Okay, embarrassingly it turns out we didn't include the migration script in Beta 5 of Calendar. However, it wouldn't work exactly that way automatically for you. You would have to revert your database back and attempt at least Calendar upgrade from v1 to v2 again. But, because of our mistake, there's an easy way for you to get your site ready for the next update (beta 6) and get the migration to happen:

1) Wait for Beta 6 to become available, and then update to it. Wait for the "Finish Up" button.
2) When you see the Finish Up button, go into your database and change the version number of the Calendar plugin from `2.0.0-beta.5` to `1.9.9`.
3) Then run the Finish Up button. It should fool the system and run the Cal v1 to v2 migration.

Sorry for the trouble :/

**Comment by davist11** [comment]
Got it, thanks for the info

**Comment by davist11** [comment]
I followed those steps, and I'm still having an issue

**Comment by kjmartens** [comment]
I'm curious if Craft automatically reverted the version number back to 2.0.0-beta.5 instead of keeping it at 1.9.9. We just released Freeform 2 beta 12, which attempts to resolve the odd migration issue you encountered. Are you able to retry the Calendar 1 -> 2 and Freeform 1 -> 2 migration again?

**Comment by davist11** [comment]
So, I've upgraded to Calendar Beta 6. Went into the DB and changed the version number to 1.9.9, then visited the CP. I don't get any finish up button. Do I have to change the schemaVersion as well?

I'm also at the point where I was ready to completely uninstall the plugin and reconfigure, but when I try and uninstall the plugin, Craft gives the error: `Couldn’t uninstall plugin.`

**Comment by kjmartens** [comment]
I think the best approach here would be to revert your site back to an earlier backup you would have taken before upgrading from Calendar 1 to Calendar 2 and try that all over again. I feel like manipulating version numbers at this point won't be reliable enough to know if that is for sure working. What's likely happened here is that the full beta 6 update ran and finished without an opportunity to "hijack" it.

**Comment by davist11** [comment]
Unfortunately we have invested too much time after finishing the Craft 3 upgrade manipulating other fields and adding additional data. I just need to get to the point where I can uninstall it and reinstall. I didn't see much explanation in the logs about why the plugin couldn't be uninstalled. Any guidance on how to manually uninstall?

**Comment by davist11** [comment]
Ah, did track down some info when trying to uninstall

```
2018-03-22 11:13:51 [::1][1][-][trace][yii\base\Controller::runAction] Route to run: plugins/uninstall-plugin
2018-03-22 11:13:51 [::1][1][-][trace][yii\base\InlineAction::runWithParams] Running action: craft\controllers\PluginsController::actionUninstallPlugin()
2018-03-22 11:13:51 [::1][1][-][trace][yii\db\Transaction::begin] Begin transaction
2018-03-22 11:13:51 [::1][1][-][info][craft\db\MigrationManager::migrateDown] Reverting Install
2018-03-22 11:13:51 [::1][1][-][trace][yii\db\Transaction::begin] Set savepoint 1
2018-03-22 11:13:51 [::1][1][-][info][yii\db\Command::execute] SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][profile begin][yii\db\Command::execute] SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][profile end][yii\db\Command::execute] SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][info][yii\db\Command::query] SHOW TABLES
2018-03-22 11:13:51 [::1][1][-][profile begin][yii\db\Command::query] SHOW TABLES
2018-03-22 11:13:51 [::1][1][-][profile end][yii\db\Command::query] SHOW TABLES
2018-03-22 11:13:51 [::1][1][-][info][yii\db\Command::execute] ALTER TABLE `craft_calendar_calendars` DROP FOREIGN KEY `calendar_calendars_fieldLayoutId_fk`
2018-03-22 11:13:51 [::1][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `craft_calendar_calendars` DROP FOREIGN KEY `calendar_calendars_fieldLayoutId_fk`
2018-03-22 11:13:51 [::1][1][-][profile end][yii\db\Command::execute] ALTER TABLE `craft_calendar_calendars` DROP FOREIGN KEY `calendar_calendars_fieldLayoutId_fk`
2018-03-22 11:13:51 [::1][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2018-03-22 11:13:51 [::1][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][warning][craft\db\mysql\Schema::rollBackSavepoint] Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2018-03-22 11:13:51 [::1][1][-][error][craft\db\MigrationManager::migrateDown] Failed to revert Install (time: 0.039s). Output:
    > drop foreign key calendar_calendars_fieldLayoutId_fk from table {{%calendar_calendars}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'calendar_calendars_fieldLayoutId_fk'; check that column/key exists
The SQL being executed was: ALTER TABLE `craft_calendar_calendars` DROP FOREIGN KEY `calendar_calendars_fieldLayoutId_fk` (/Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cr...')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE `cr...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Migration.php(479): yii\db\Command->execute()
#3 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-commons/src/Migrations/StreamlinedInstallMigration.php(63): yii\db\Migration->dropForeignKey('calendar_calend...', '{{%calendar_cal...')
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Migration.php(73): Solspace\Commons\Migrations\StreamlinedInstallMigration->safeDown()
#5 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(297): craft\db\Migration->down(true)
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/base/Plugin.php(141): craft\db\MigrationManager->migrateDown(Object(Solspace\Calendar\migrations\Install))
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Plugins.php(514): craft\base\Plugin->uninstall()
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/PluginsController.php(67): craft\services\Plugins->uninstallPlugin('calendar')
#9 [internal function]: craft\controllers\PluginsController->actionUninstallPlugin()
#10 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('uninstall-plugi...', Array)
#13 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('uninstall-plugi...', Array)
#14 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('plugins/uninsta...', Array)
#15 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('plugins/uninsta...', Array)
#16 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#19 {main}
```

**Comment by davist11** [comment]
🙌  that worked! Thanks for much for breaking all that down to get the migration completed.
