### ISSUE TITLE
error: Undefined array key "titleTranslationMethod"

### ISSUE THREAD

**Issue by dgrigg** [solspace/craft3-calendar#212]
Seeing this error when attempt to run the ./craft project-config/apply

```
Applying changes from your project config files ...
- adding solspace.calendar.calendars.2148eced-c8de-40aa-a523-4d0d7ef608d8.fieldLayout.tabs.0.elements.0 ... 
  - adding solspace.calendar.calendars.2148eced-c8de-40aa-a523-4d0d7ef608d8 ... 
error: Undefined array key "titleTranslationMethod"
```
And this in the logs

```
2023-02-28 23:40:02 [console.ERROR] [yii\base\ErrorException:2] Undefined array key "titleTranslationMethod" {"trace":["#0 /home/forge/cedarview.org/vendor/solspace/craft-calendar/packages/plugin/src/Bundles/ProjectConfig/CalendarProjectConfig.php(45): yii\\base\\ErrorHandler->handleError()","#1 /home/forge/cedarview.org/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): Solspace\\Calendar\\Bundles\\ProjectConfig\\CalendarProjectConfig->handleChange()","#2 [internal function]: craft\\services\\ProjectConfig->handleChangeEvent()","#3 /home/forge/cedarview.org/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()","#4 /home/forge/cedarview.org/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\\base\\Component->trigger()","#5 /home/forge/cedarview.org/vendor/craftcms/cms/src/services/ProjectConfig.php(1115): craft\\models\\ProjectConfigData->commitChanges()","#6 [internal function]: craft\\services\\ProjectConfig->handleChangeEvent()","#7 /home/forge/cedarview.org/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()","#8 /home/forge/cedarview.org/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\\base\\Component->trigger()","#9 /home/forge/cedarview.org/vendor/craftcms/cms/src/services/ProjectConfig.php(1231): craft\\models\\ProjectConfigData->commitChanges()","#10 /home/forge/cedarview.org/vendor/craftcms/cms/src/services/ProjectConfig.php(1253): craft\\services\\ProjectConfig->craft\\services\\{closure}()","#11 /home/forge/cedarview.org/vendor/craftcms/cms/src/services/ProjectConfig.php(577): craft\\services\\ProjectConfig->_applyChanges()","#12 /home/forge/cedarview.org/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(303): craft\\services\\ProjectConfig->applyExternalChanges()","#13 [internal function]: craft\\console\\controllers\\ProjectConfigController->actionApply()","#14 /home/forge/cedarview.org/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#15 /home/forge/cedarview.org/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#16 /home/forge/cedarview.org/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction()","#17 /home/forge/cedarview.org/vendor/craftcms/cms/src/console/Controller.php(227): yii\\console\\Controller->runAction()","#18 /home/forge/cedarview.org/vendor/yiisoft/yii2/base/Module.php(552): craft\\console\\Controller->runAction()","#19 /home/forge/cedarview.org/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction()","#20 /home/forge/cedarview.org/vendor/craftcms/cms/src/console/Application.php(90): yii\\console\\Application->runAction()","#21 /home/forge/cedarview.org/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction()","#22 /home/forge/cedarview.org/vendor/craftcms/cms/src/console/Application.php(121): yii\\console\\Application->handleRequest()","#23 /home/forge/cedarview.org/vendor/yiisoft/yii2/base/Application.php(384): craft\\console\\Application->handleRequest()","#24 /home/forge/cedarview.org/craft(13): yii\\base\\Application->run()","#25 {main}"],"memory":37463496,"exception":"[object] (yii\\base\\ErrorException(code: 2): Undefined array key \"titleTranslationMethod\" at /home/forge/cedarview.org/vendor/solspace/craft-calendar/packages/plugin/src/Bundles/ProjectConfig/CalendarProjectConfig.php:45)"} 

```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.10 Pro
- Calendar Version: 4.0.6
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @dgrigg,

I'm very sorry for the trouble and the delay...

Is this still an issue for you, or did you happen to figure it out? If not, I'm curious what your flow was for updating both Calendar and the project config. That might give us a clue as to how this could have happened. 🙂

**Comment by dgrigg** [comment]
@kjmartens I was able to get it working. I updated the composer file for the latest version 4 compatible plugins, ran composer install and then ./craft up to run the migrations. That's where it errored out.

**Comment by kjmartens** [comment]
Thanks! Glad you were able to figure it out. 🙂

**Comment by mikejpeters** [comment]
We hit the same error, and the solution was to rebuild the project config from the database.

My guess is that we configured our calendars on a fairly old version of Craft, before `titleTranslationKeyFormat` and `titleTranslationMethod` were written to the project config, but the `CalendarProjectConfig#handleChange()` method doesn't handle this
