### ISSUE TITLE
3.3.0 doesn't work with PostgreSQL

### ISSUE THREAD

**Issue by boboldehampsink** [solspace/craft3-calendar#40]
It seems table names are not properly quoted in the migration. 

<img width="1479" alt="Screen Shot 2021-05-28 at 09 26 24" src="https://user-images.githubusercontent.com/378974/119946394-e1400180-bf96-11eb-8f30-2a6697a78d25.png">

**Comment by kjmartens** [comment]
Sorry for the trouble @boboldehampsink. We'll get on this shortly. :)

**Comment by kjmartens** [comment]
@boboldehampsink If you'd like to try out the fix now, you can set your main Craft **composer.json** file to `dev-master` for Calendar version and run composer update:

```
"solspace/craft-freeform": "dev-master"
```

**Comment by boboldehampsink** [comment]
Thanks, looks good!

**Comment by gustavs-gutmanis** [comment]
Glad to hear

**Comment by boboldehampsink** [comment]
Now seeing the same error again in 3.3.1

**Comment by kjmartens** [comment]
Sorry for the trouble @boboldehampsink. We'll check into it again shortly.

**Comment by kjmartens** [comment]
This should be resolved now in Calendar 3.3.2 :)

**Comment by boboldehampsink** [comment]
@kjmartens thanks, but now installation fails with this error:

```


> applying existing project config ... Exception: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "calendar_calendars_handle_key"
--
  | DETAIL:  Key (handle)=(default) already exists.
  | The SQL being executed was: INSERT INTO "calendar_calendars" ("uid", "name", "handle", "description", "color", "descriptionFieldHandle", "locationFieldHandle", "icsHash", "icsTimezone", "titleFormat", "titleLabel", "hasTitleField", "allowRepeatingEvents", "fieldLayoutId", "dateCreated", "dateUpdated") VALUES ('09017459-0e3f-4241-957a-759fe090fe3d', 'Algemeen', 'default', '', '#57617A', 'introduction', NULL, NULL, 'floating', NULL, 'Titel', TRUE, TRUE, 1, '2021-07-07 06:21:04', '2021-07-07 06:21:04') (/app/user/vendor/yiisoft/yii2/db/Schema.php:678)
  | #0 /app/user/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "ca...')
  | #1 /app/user/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO "ca...')
  | #2 /app/user/vendor/solspace/craft3-calendar/packages/plugin/src/Bundles/ProjectConfig/CalendarProjectConfig.php(54): yii\db\Command->execute()
  | #3 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1185): Solspace\Calendar\Bundles\ProjectConfig\CalendarProjectConfig->handleChange(Object(craft\events\ConfigEvent))
  | #4 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
  | #5 /app/user/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
  | #6 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(745): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #7 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1175): craft\services\ProjectConfig->_processConfigChangesInternal('solspace.calend...')
  | #8 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
  | #9 /app/user/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
  | #10 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(745): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #11 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1303): craft\services\ProjectConfig->_processConfigChangesInternal('solspace.calend...', false, NULL, true)
  | #12 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(569): craft\services\ProjectConfig->_applyChanges(Array)
  | #13 /app/user/vendor/craftcms/cms/src/migrations/Install.php(1102): craft\services\ProjectConfig->applyYamlChanges()
  | #14 /app/user/vendor/craftcms/cms/src/migrations/Install.php(74): craft\migrations\Install->insertDefaultData()
  | #15 /app/user/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\Install->safeUp()
  | #16 /app/user/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
  | #17 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(179): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
  | #18 [internal function]: craft\console\controllers\InstallController->actionCraft()
  | #19 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #20 /app/user/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
  | #21 /app/user/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('', Array)
  | #22 /app/user/vendor/craftcms/cms/src/console/Controller.php(192): yii\console\Controller->runAction('', Array)
  | #23 /app/user/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('', Array)
  | #24 /app/user/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('install', Array)
  | #25 /app/user/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('install', Array)
  | #26 /app/user/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('install', Array)
  | #27 /app/user/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #28 /app/user/craft(24): yii\base\Application->run()
  | #29 {main}

```

**Comment by gustavs-gutmanis** [comment]
Could you provide us with your `composer.json`, `composer.lock` and `config/project` files?  
It seems like you're installing a fresh craft install on an existing database.

**Comment by boboldehampsink** [comment]
I'm doing a fresh install with an existing project config, but empty database

**Comment by gustavs-gutmanis** [comment]
Then it might be because of the `Calendar::afterInstall` hook, which adds a default calendar. I will check it out

**Comment by boboldehampsink** [comment]
@gustavs-gutmanis yeah it should only do that when there is no calendar yet
